name: flutter_application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.0.3

  intl: ^0.17.0

  table_calendar: ^3.0.6

  shared_preferences: ^2.0.15

  google_fonts: ^3.0.1

  dio: ^4.0.6
  
  url_launcher: ^6.1.3
  badges: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

